drop table if exists actor;
drop table if exists character_role;
drop table if exists company;
drop table if exists company_movies;
drop table if exists country;
drop table if exists country_movies;
drop table if exists genre;
drop table if exists genre_movies;
drop table if exists movie;
drop table if exists spoken_language;
drop table if exists spoken_language_movies;
drop table if exists actor;
drop table if exists character_role;
drop table if exists company;
drop table if exists company_movies;
drop table if exists country;
drop table if exists country_movies;
drop table if exists genre;
drop table if exists genre_movies;
drop table if exists movie;
drop table if exists spoken_language;
drop table if exists spoken_language_movies;
alter table character_role drop foreign key FK12jxlphendn29pudohnio8ymm;
alter table character_role drop foreign key FKdn791samgdthk1gqaasgepvxk;
alter table company_movies drop foreign key FKmmc8rt6ss635b1nrybown4va2;
alter table company_movies drop foreign key FKknnnj0j6wcph9jgfn2bcd4ky6;
alter table country_movies drop foreign key FKpygrtf1pvsg7g61jprlk308m8;
alter table country_movies drop foreign key FKpxkrflndnuuvgs4n7pj2sqlpx;
alter table genre_movies drop foreign key FKtgatsvi7lb98phh9ft1gogkep;
alter table genre_movies drop foreign key FKe8j9am8l355522fj88clwhbt8;
alter table spoken_language_movies drop foreign key FK8hthayk0ncohnquu6m4awhjby;
alter table spoken_language_movies drop foreign key FK89oep3w39yoikhvgykrq16mb1;
drop table if exists actor;
drop table if exists character_role;
drop table if exists company;
drop table if exists company_movies;
drop table if exists country;
drop table if exists country_movies;
drop table if exists genre;
drop table if exists genre_movies;
drop table if exists movie;
drop table if exists spoken_language;
drop table if exists spoken_language_movies;
alter table character_role drop foreign key FK12jxlphendn29pudohnio8ymm;
alter table character_role drop foreign key FKdn791samgdthk1gqaasgepvxk;
alter table company_movies drop foreign key FKmmc8rt6ss635b1nrybown4va2;
alter table company_movies drop foreign key FKknnnj0j6wcph9jgfn2bcd4ky6;
alter table country_movies drop foreign key FKpygrtf1pvsg7g61jprlk308m8;
alter table country_movies drop foreign key FKpxkrflndnuuvgs4n7pj2sqlpx;
alter table genre_movies drop foreign key FKtgatsvi7lb98phh9ft1gogkep;
alter table genre_movies drop foreign key FKe8j9am8l355522fj88clwhbt8;
alter table spoken_language_movies drop foreign key FK8hthayk0ncohnquu6m4awhjby;
alter table spoken_language_movies drop foreign key FK89oep3w39yoikhvgykrq16mb1;
drop table if exists actor;
drop table if exists character_role;
drop table if exists company;
drop table if exists company_movies;
drop table if exists country;
drop table if exists country_movies;
drop table if exists genre;
drop table if exists genre_movies;
drop table if exists movie;
drop table if exists spoken_language;
drop table if exists spoken_language_movies;
drop table if exists actor cascade ;
drop table if exists character_role cascade ;
drop table if exists company cascade ;
drop table if exists company_movies cascade ;
drop table if exists country cascade ;
drop table if exists country_movies cascade ;
drop table if exists genre cascade ;
drop table if exists genre_movies cascade ;
drop table if exists movie cascade ;
drop table if exists spoken_language cascade ;
drop table if exists spoken_language_movies cascade ;
drop table if exists actor cascade ;
drop table if exists character_role cascade ;
drop table if exists company cascade ;
drop table if exists company_movies cascade ;
drop table if exists country cascade ;
drop table if exists country_movies cascade ;
drop table if exists genre cascade ;
drop table if exists genre_movies cascade ;
drop table if exists movie cascade ;
drop table if exists spoken_language cascade ;
drop table if exists spoken_language_movies cascade ;
