create table employment (id integer generated by default as identity (start with 1), title varchar(255), key_skills varchar(255), person_id integer, primary key (id));
create table person (id integer generated by default as identity (start with 1), first_name varchar(255), last_name varchar(255), primary key (id));
alter table employment add constraint FK81ihijcn1kdfwffke0c0sjqeb foreign key (person_id) references person;

